# Generated by Django 4.0.4 on 2022-06-02 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Expenses', '0002_alter_category_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
