# Generated by Django 4.0.4 on 2022-06-02 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserPreferences', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpreferences',
            name='currency',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
